# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/api/v1/plays', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Play. As you add validations to Play, be sure to
  # adjust the attributes here as well.
  let(:user) { create(:user) }

  let(:valid_attributes) do
    attributes_for(:play, user_id: user.id, game_id: create(:game).id)
  end

  let(:invalid_attributes) do
    attributes_for(:play, user_id: nil, game_id: nil)
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # PlaysController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    { Authorization: JsonWebToken.encode(user_id: user.id) }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Play.create! valid_attributes
      get api_v1_plays_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      play = Play.create! valid_attributes
      get api_v1_play_url(play), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Play' do
        expect do
          post api_v1_plays_url,
               params: { play: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Play, :count).by(1)
      end

      it 'renders a JSON response with the new play', :aggregate_failures do
        post api_v1_plays_url,
             params: { play: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Play' do
        expect do
          post api_v1_plays_url,
               params: { play: invalid_attributes }, as: :json
        end.to change(Play, :count).by(0)
      end

      it 'renders a JSON response with errors for the new play', :aggregate_failures do
        post api_v1_plays_url,
             params: { play: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { minutes_played: 300 }
      end

      it 'updates the requested play' do
        play = Play.create! valid_attributes
        patch api_v1_play_url(play),
              params: { play: new_attributes }, headers: valid_headers, as: :json
        play.reload
        expect(play.minutes_played).to eq(new_attributes[:minutes_played])
      end

      it 'renders a JSON response with the play', :aggregate_failures do
        play = Play.create! valid_attributes
        patch api_v1_play_url(play),
              params: { play: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the play', :aggregate_failures do
        play = Play.create! valid_attributes
        patch api_v1_play_url(play),
              params: { play: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested play' do
      play = Play.create! valid_attributes
      expect do
        delete api_v1_play_url(play), headers: valid_headers, as: :json
      end.to change(Play, :count).by(-1)
    end
  end
end
