env:
  RUBY_VERSION: 2.7.1

name: Rails tests
on: [push, pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop rubocop-performance rubocop-rails rubocop-rspec
      - name: Check code
        run: rubocop
  rspec-test:
    name: RSpec
    needs: [rubocop-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - name: Install dependencies
      run: |
        gem install bundler  
        bundle install
    - name: Create database
      run: |
        bundler exec rails db:create RAILS_ENV=test
        bundler exec rails db:migrate RAILS_ENV=test
    - name: Run tests
      run: bundle exec rake
