env:
  RUBY_VERSION: 2.7.2

name: Rails tests
on: [push, pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Check code
        run: bundle exec rubocop
  rspec-test:
    name: RSpec
    needs: [rubocop-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Create database
      run: |
        bundler exec rails db:create RAILS_ENV=test
        bundler exec rails db:migrate RAILS_ENV=test
    - name: Run tests
      run: bundle exec rspec
    - name: Upload coverage results    
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: coverage-report
        path: coverage

